name: flutter_graphql
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dart_graphql_client:
    path: dart_graphql_client

  cupertino_icons: ^1.0.2

  uuid: ^3.0.6
  get_it: ^7.2.0
  ferry: ^0.10.4
  ferry_flutter: ^0.5.4
  gql_http_link: ^0.4.0
  flutter_slidable: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  ferry_generator: ^0.4.4

flutter:
  uses-material-design: true
