name: dart_graphql_client
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  ferry: ^0.10.4
  gql_http_link: ^0.4.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_runner: ^2.1.7
  ferry_generator: ^0.4.4
